#+TITLE: Org-mode
#+AUTHOR: Ashkan Mirzaee
#+LANGUAGE: en
#+OPTIONS: H:2 num:nil toc:nil

[[https://orgmode.org][Org website]] describes "Org mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system". Org-mode in Emacs is very similar to Markdown that let you combine text and codes and evaluate codes and generate PDF or HTML outputs. Following are great resources to learn Org:
- [[https://orgmode.org/worg/org-tutorials/org4beginners.html][Org mode beginning at the basics]] 
- [[https://orgmode.org/worg/org-tutorials/index.html][Org tutorials]]

Recent [[https://www.gnu.org/software/emacs/][Emacs]] includes Org mode, to begin, use =emacs test.org= to create an Org file by Emacs.

*** Introduction
Let's learn how use *org-mode* to:
- insert headlines (=M-enter=) \- press =M-enter= to go to the next line
- move headlines up and down (=M-up/down=)
- fold/unfold (=tab/S-tab=)
- insert blocks 
  - example (=<e-tab=)
  - source code (=<s-tab=) 
    - for example org/bash/python
- create tables
- create TODO items
- save (=C-x C-s=), export (=C-c C-e=), and exit (=C-x C-c=)
  - use =C-c C-e= and press =h= and then =o= to see HTML output 

Let's try them in Emacs by (I used =<s-tab org= to create the block in below):

#+BEGIN_SRC org
 ** Introduction
 Let's learn how use *org-mode* to:
 - insert headlines (=M-enter=) - press =M-enter= to go to the next line
 - move headlines up and down (=M-up/down=)
 - fold/unfold (=tab/S-tab=)
 - insert blocks 
   - example (=<e-tab=)
   - source code (=<s-tab=) 
     - for example org/bash/python
 - create tables
 - create TODO items
 - save (=C-x C-s=), export (=C-c C-e=), and exit (=C-x C-c=)
   - use =C-c C-e= and press =h= and then =o= to see HTML output
#+END_SRC

Use =M-up/down= to see how easy you can move headlines and use =C-c C-e h o= to see the outputs in your browser.

*Note* that /unordered/ lists start with *-,+,or \** and /ordered/ lists start with *a number and a dot* and descriptions use *::*.

- *For example* :: This is an examle of a /discription/

And this is an orderd list:
1. First (press =M-enter=)
2. Second (press =M-enter=)
3. Third is a link to [[https://orgmode.org/][org-mode]] website

#+BEGIN_SRC org
 *Note* that /unordered/ lists start with *-,+,or \** and /ordered/ lists start with *a number and a dot* and descriptions use *::*.
 
 - *For example* :: This is an example of a /description/

 And this is an ordered list:
 1. First (press =M-enter=)
 2. Second (press =M-enter=)
 3. Third is a link to [ [https://orgmode.org/][org-mode] ] website
#+END_SRC

*** Tables
The following is the key abbreviations:
 
| Name    | key   | Abbr. |
|---------+-------+-------|
| Control | Ctrl  | C     |
| Meta    | Alt   | M     |
| Shift   | Shift | S     |
| Return  | Enter | RET   |

#+BEGIN_SRC org                              
| Name    | key   | Abbr. |
|---------+-------+-------|
| Control | Ctrl  | C     |
| Meta    | Alt   | M     |
| Shift   | Shift | S     |
| Return  | Enter | RET   |
#+END_SRC 

Note that to create above table you only need to insert =|Name|Key|Abbr.= and press =tab= to make new row and insert =-tab= to draw the hline and press =tab=. Also you can use (these might be different in different OS):
- =M-up/down= to move rows
- =M-left/right= to move columns
- =M-S-up/down= to add/remove rows 
- =M-S-left/right= to add/remove columns 

You also use =<c>=, =<l>= or =<r>= for center, left or right align.

*** Basic TODO
To create a TODO list you only need:

#+BEGIN_SRC org
 ** TODO learn org-mode
 ** DONE learn emacs
    DEADLINE: <2019-11-16 Sat>
#+END_SRC

To change a TODO task to DONE or remove it use =S-left/right=. Use =C-c C-d= to add a deadline.

*** LaTeX
We can use LaTeX to write equations in Org. For example:

#+BEGIN_SRC latex                
\begin{equation}              
x=\sqrt{b}            
\end{equation}
If $a^2=b$ and $b=2$, then the solution must be either $$a=+\sqrt{2}$$ or $$a=-\sqrt{2}$$ 
#+END_SRC

Org processes LaTeX codes in the HTML/PDF outputs.

-----
Copyright 2018-2019, [[https://ashki23.github.io/index.html][Ashkan Mirzaee]] | Content is available under [[https://creativecommons.org/licenses/by-sa/3.0/][CC BY-SA 3.0]] | Sourcecode licensed under [[https://www.gnu.org/licenses/gpl-3.0.en.html][GPL-3.0]]
